//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jumpings.Migrations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _202001242139002_InitialCreate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _202001242139002_InitialCreate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jumpings.Migrations.202001242139002_InitialCreate", typeof(_202001242139002_InitialCreate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAEAM1XyW4jNxC9B8g/EDx7RNm+JEZrBo5kB0os25j2zJ3qLslEuHRItiEhyJflkE/KL6TYu7olL5rJAl3UxapXexX51x9/Rh82SpInsE4YPaGnozEloBOTCr2e0Nyv3n1HP7z/9pvoKlUb8rnmOw98KKndhD56n10w5pJHUNyNlEiscWblR4lRjKeGnY3H37PTUwYIQRGLkOhjrr1QUHzg59ToBDKfc7kwKUhX0fEkLlDJLVfgMp7AhP6UqwyNc5RcSsFRfwxyRQnX2nju0bqLTw5ib41exxkSuHzYZoB8Ky4dVFZftOyvdWB8FhxgrWANleTOG/VGwNPzKiKsL35UXGkTMYzZFcbWb4PXRdzKkIGlpK/qYiptYGuDOipZT0hNOGlyjqURfidkmkufW5hoyL3l8oTc50spkp9h+2B+AT3RuZRde9AiPNshIOneGlTktx9hVVk5n1HCduVYX7AR68iUHsy1Pz+j5BaV86WEJt0db2NvLPwI [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
